version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siroko-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public

  db:
    image: postgres:14
    container_name: siroko-postgres
    environment:
      POSTGRES_USER: siroko
      POSTGRES_PASSWORD: siroko
      POSTGRES_DB: siroko_cart
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: siroko-adminer
    restart: always
    ports:
      - "8081:8080"
