# This file is the entry point to configure your own services. 
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    Carrito\Dominio\RepositorioCarrito: '@App\Carrito\Infraestructura\Repositorio\RepositorioCarritoDoctrine'

    App\Carrito\Infraestructura\Repositorio\RepositorioCarritoDoctrine:
        public: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
    
    App\Pedido\Dominio\RepositorioPedido: '@App\Pedido\Infraestructura\Repositorio\RepositorioPedidoDoctrine'

    App\Pedido\Infraestructura\Repositorio\RepositorioPedidoDoctrine:
        public: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'


