parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false 

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/**/Persistencia/**'

    App\Carrito\Infraestructura\Controlador\:
        resource: '../src/Carrito/Infraestructura/Controlador/'
        tags: ['controller.service_arguments']

    App\Pedido\Infraestructura\Controlador\:
        resource: '../src/Pedido/Infraestructura/Controlador/'
        tags: ['controller.service_arguments']

    Carrito\Dominio\RepositorioCarrito: '@App\Carrito\Infraestructura\Repositorio\RepositorioCarritoDoctrine'
    App\Carrito\Infraestructura\Repositorio\RepositorioCarritoDoctrine:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    Pedido\Dominio\RepositorioPedido: '@App\Pedido\Infraestructura\Repositorio\RepositorioPedidoDoctrine'
    App\Pedido\Infraestructura\Repositorio\RepositorioPedidoDoctrine:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
