# config/services.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    Carrito\Dominio\RepositorioCarrito: '@App\Carrito\Infraestructura\Repositorio\RepositorioCarritoDoctrine'

    App\Carrito\Infraestructura\Repositorio\RepositorioCarritoDoctrine:
        public: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
    
    App\Pedido\Dominio\RepositorioPedido: '@App\Pedido\Infraestructura\Repositorio\RepositorioPedidoDoctrine'

    App\Pedido\Infraestructura\Repositorio\RepositorioPedidoDoctrine:
        public: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # 👇 Añadido explícitamente para test
    App\Pedido\Infraestructura\Controlador\ProcesarCheckoutController:
        public: true
        autowire: true
        autoconfigure: true
